### PR TITLE
fix: referral buyback weight

### LINKED ISSUE #1286: Bug: maxed out mandatory weight
the mandatory weight stored with block seems to be overstated and ultimatelly maxed out to the limits

e.g.
```
{
  normal: {
    refTime: 2,847,255,000
    proofSize: 19,424
  }
  operational: {
    refTime: 0
    proofSize: 0
  }
  mandatory: {
    refTime: 1,996,458,565,511
    proofSize: 7,688,558
  }
}
```

in random block mandatory weight is reported to be `2 sec - normal weight` which is not reality. mandatory weight should be mostly constant only influenced by the dca, ema or other on initialize processes.

real weight and pov reported by collators is much smaller:
```
{"log":"2025-12-15 14:08:55 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 24.6083984375kb, storage_proof: 67.7001953125kb }\n","stream":"stderr","time":"2025-12-15T14:08:55.069557472Z"}
{"log":"2025-12-15 14:10:49 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 24.783203125kb, storage_proof: 329.64453125kb }\n","stream":"stderr","time":"2025-12-15T14:10:49.202735087Z"}
{"log":"2025-12-15 14:12:42 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 24.791015625kb, storage_proof: 307.8876953125kb }\n","stream":"stderr","time":"2025-12-15T14:12:42.834333262Z"}
{"log":"2025-12-15 14:14:36 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 24.7822265625kb, storage_proof: 105.1572265625kb }\n","stream":"stderr","time":"2025-12-15T14:14:36.465923432Z"}
{"log":"2025-12-15 14:16:31 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 24.6083984375kb, storage_proof: 366.373046875kb }\n","stream":"stderr","time":"2025-12-15T14:16:31.122008958Z"}
{"log":"2025-12-15 14:18:24 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 24.6083984375kb, storage_proof: 67.9052734375kb }\n","stream":"stderr","time":"2025-12-15T14:18:25.005015642Z"}
{"log":"2025-12-15 14:20:18 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 22.5205078125kb, storage_proof: 59.9248046875kb }\n","stream":"stderr","time":"2025-12-15T14:20:18.48766268Z"}
{"log":"2025-12-15 14:22:12 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 24.7470703125kb, storage_proof: 98.6533203125kb }\n","stream":"stderr","time":"2025-12-15T14:22:12.820838935Z"}
{"log":"2025-12-15 14:24:06 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 24.76953125kb, storage_proof: 98.7890625kb }\n","stream":"stderr","time":"2025-12-15T14:24:06.452701792Z"}
{"log":"2025-12-15 14:26:00 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 24.6083984375kb, storage_proof: 67.6962890625kb }\n","stream":"stderr","time":"2025-12-15T14:26:00.334674953Z"}
{"log":"2025-12-15 14:27:54 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 24.6083984375kb, storage_proof: 67.6259765625kb }\n","stream":"stderr","time":"2025-12-15T14:27:54.567359474Z"}
{"log":"2025-12-15 14:27:54 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 24.6083984375kb, storage_proof: 67.6259765625kb }\n","stream":"stderr","time":"2025-12-15T14:27:54.617488649Z"}
{"log":"2025-12-15 14:29:48 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 24.6083984375kb, storage_proof: 67.3505859375kb }\n","stream":"stderr","time":"2025-12-15T14:29:48.550243823Z"}
{"log":"2025-12-15 14:31:42 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 24.6083984375kb, storage_proof: 67.3974609375kb }\n","stream":"stderr","time":"2025-12-15T14:31:42.432552186Z"}
{"log":"2025-12-15 14:31:42 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 24.6083984375kb, storage_proof: 67.3974609375kb }\n","stream":"stderr","time":"2025-12-15T14:31:42.983228341Z"}
{"log":"2025-12-15 14:33:36 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 22.6923828125kb, storage_proof: 95.1591796875kb }\n","stream":"stderr","time":"2025-12-15T14:33:36.765978116Z"}
{"log":"2025-12-15 14:35:30 [Parachain] PoV size { header: 0.3310546875kb, extrinsics: 22.5205078125kb, storage_proof: 377.57421875kb }\n","stream":"stderr","time":"2025-12-15T14:35:30.39799366Z"}
```

it is possible that:
- there is some miscalculation of mandatory weight
- the remainer of mandatory weight is being filled, possibly by some inherent with unbounded weight
- possibly related to 6 second block change

### PR DESCRIPTION
**Pull request by cl0w5**
This PR fixes the mandatory block size which is reported as consumed, by making sure that pallet_referrals on_idle does not report more weight than it exhausts

Fixes #1286 

Before:
```{
  normal: {
    refTime: 0
    proofSize: 0
  }
  operational: {
    refTime: 0
    proofSize: 0
  }
  mandatory: {
    refTime: 1,997,352,790,511
    proofSize: 7,826,445
  }
}
```

After:
```{
  normal: {
    refTime: 0
    proofSize: 0
  }
  operational: {
    refTime: 0
    proofSize: 0
  }
  mandatory: {
    refTime: 13,641,669,511
    proofSize: 292,104
  }
}
```

### CODE REVIEW

File: pallets/referrals/src/lib.rs [hunk 1]
```diff
@@ -608,8 +608,17 @@ pub mod pallet {
...
 			let one_read = T::DbWeight::get().reads(1u64);
-			let max_converts = remaining_weight.saturating_sub(one_read).ref_time() / convert_weight.ref_time();
+			let remaining = remaining_weight.saturating_sub(one_read);
 
+			// Consider both ref_time and proof_size to determine max conversions
+			let max_by_ref_time = remaining.ref_time().checked_div(convert_weight.ref_time()).unwrap_or(0);
+			let max_by_proof_size = remaining
+				.proof_size()
+				.checked_div(convert_weight.proof_size())
+				.unwrap_or(u64::MAX);
```
Comment (dmoka) [inline pallets/referrals/src/lib.rs]: what is the reason that we default to max in case of dividing by 0?

Comment (cl0w5) [reply pallets/referrals/src/lib.rs]: if convert_weight.proof_size is 0 (the case where this would fail), proof size is not a constraint - as the proof size of the operation is 0, in theory it could to any amount of operations from the point of view of proof size

Comment (cl0w5) [reply pallets/referrals/src/lib.rs]: actually, it is probably better to return 0 here and skip it all-together

Comment (cl0w5) [reply pallets/referrals/src/lib.rs]: done!
