### PR TITLE
fix: EVM nonce increasing twice

### LINKED ISSUE #1199: Bug: nonce incremented multiple times in batch
- [ ] #1223

### PR DESCRIPTION
**Pull request by F3Joule**
## Description
The Pull Request introduces changes to improve the handling of EVM transactions and their nonce behavior, particularly for batch calls and permit-based dispatches, as well as adjustments to avoid unintended nonce increments. It also adds new test cases to validate these updates

## Related Issue
Fixes #1199 

## Checklist:

- [ ] I have updated the documentation if necessary.
- [X] I have added tests to cover my changes, regression test if fixing an issue.
- [ ] This is a breaking change.

### CODE REVIEW

File: integration-tests/src/evm.rs [hunk 1]
```diff
@@ -95,6 +98,8 @@ mod account_conversion {
 	}
 
 	#[test]
+	// FIXME: will not pass, because nonce is increase by Executive;
+	// 	needs to mock SignedExtra and do UncheckedExtrinsic::new_signed and apply_extrinsic
 	fn bind_address_should_fail_when_nonce_is_not_zero() {
```
Comment (F3Joule) [inline integration-tests/src/evm.rs]: We already have unit test for this case:
https://github.com/galacticcouncil/hydration-node/blob/29f1b9e954d176d3168b26a0cd275bd6ffe7116d/pallets/evm-accounts/src/tests.rs#L102-L113

But to make a regression test correctly, we need to mock `Executive` and its dependencies (`UncheckedExtrinsic`, `SignedExtra`, etc.), because nonce isn't increased with just dispatching calls, it's increased for extrinsic by `CheckNonce` extra in `Executive`

**Review by enthusiastmartin — APPROVED** [review]
